#!/bin/bash
NUM_ENVS=$1
START_PORT=$2
echo "Running artisynth: " $NUM_ENVS $START_PORT

for (( p=$START_PORT; p<$START_PORT+$NUM_ENVS; p++ ))
do
echo "run artisynth at port:" $p
artisynth -model artisynth.models.lumbarSpine.RlLumbarSpine [ -port $p ] -play -noTimeline -noGui &
done
