#!/bin/bash
LOAD_PATH=$2
PORT=$1

echo "Testing"
echo "Model: " $LOAD_PATH
echo "Port: " $PORT

python3 ../src/main.py --env-name=SpineEnv-v0 --model-name=test \
--log-interval=1 --wait-action=0.0 --eval-interval=1 --verbose=20 \
--num-steps-eval=5000 --algo=ppo --num-processes=1 --port=$PORT --load-path=$LOAD_PATH \
--test

