#!/bin/bash

python3 ../src/main.py --env-name=SpineEnv-v0 --model-name=ppo-obsSize18-exc-expReward-noVecNorm-manyStates-15procs-wait0.3-done10-clipUpperRatio --log-interval=1 --num-steps=32 --save-interval=4 --wait-action=0.3 --eval-interval=1 --verbose=20 --num-steps-eval=5 --ppo-epoch=4 --algo=ppo --num-processes=15 --port=4545 --use-wandb --num-env-steps=10000 --num-mini-batch=16 --reset-step=30 --entropy-coef=0.0001 --lr=1e-6 --clip-param=0.5 --hidden-layer-size=256 --resume-wandb --use-linear-lr-decay --use-linear-clip-decay
